## what is tensor ?

![image.png](images/from_1d_tensor.png)

![image.png](images/from_2d_tensor.png)

![image.png](images/from_3d_tensor.png)

![image.png](images/why_are_tensor_useful.png)

![image.png](images/where_are_tensor_used_in_deep_learning.png)

# Creating Tensor and practical from here ""

In [1]:
import torch

In [2]:
a = torch.tensor([1, 2, 3])
print(a)

tensor([1, 2, 3])


In [12]:
a= torch.empty(2, 2,2)
print(a)

tensor([[[2.1229e-14, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[5.3328e-14, 0.0000e+00],
         [1.2986e-13, 0.0000e+00]]])


In [13]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
import random
random.seed(100)
random.random()*10      #core part of seed come from here 

1.4566925510413031

In [22]:
torch.range(1, 10,2)

/tmp/ipykernel_424621/4252498415.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 10,2)


tensor([1., 3., 5., 7., 9.])

In [26]:
torch.linspace(1, 10,9)

tensor([ 1.0000,  2.1250,  3.2500,  4.3750,  5.5000,  6.6250,  7.7500,  8.8750,
        10.0000])

In [34]:
torch.eye(50)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [44]:
torch.tensor([1,2,3,4,True,False]) # tensor([1, 2, 3, 4, 1, 0], dtype=torch.uint8)  # True is converted to 1 and False is converted to 0

tensor([1, 2, 3, 4, 1, 0])

In [46]:
torch.full_like(torch.tensor([1, 2, 3]), 5).shape # tensor([5, 5, 5])

torch.Size([3])