## what is tensor ?

![image.png](images/from_1d_tensor.png)

![image.png](images/from_2d_tensor.png)

![image.png](images/from_3d_tensor.png)

![image.png](images/why_are_tensor_useful.png)

![image.png](images/where_are_tensor_used_in_deep_learning.png)

# Creating Tensor and practical from here ""

In [105]:
import torch

In [106]:
a = torch.tensor([1, 2, 3])
print(a)

tensor([1, 2, 3])


In [ ]:
a = torch.empty(2, 2, 2)
print(a)

tensor([[[1.3051e-13, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[1.2785e-13, 0.0000e+00],
         [1.2649e-13, 0.0000e+00]]])


In [108]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
import random

random.seed(100)
random.random() * 10  # core part of seed come from here

1.4566925510413031

In [ ]:
torch.range(1, 10, 2)

/tmp/ipykernel_424621/4252498415.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 10,2)


tensor([1., 3., 5., 7., 9.])

In [ ]:
torch.linspace(1, 10, 9)

tensor([ 1.0000,  2.1250,  3.2500,  4.3750,  5.5000,  6.6250,  7.7500,  8.8750,
        10.0000])

In [112]:
torch.eye(50)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [ ]:
torch.tensor(
    [1, 2, 3, 4, True, False]
)  # tensor([1, 2, 3, 4, 1, 0], dtype=torch.uint8)  # True is converted to 1 and False is converted to 0

tensor([1, 2, 3, 4, 1, 0])

In [ ]:
torch.full_like(torch.tensor([1, 2, 3]), 5).shape  # tensor([5, 5, 5])

torch.Size([3])

In [ ]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)

In [116]:
x.to(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
print("Tensor Data Types:")
print("{:<20} {:<20}".format("Data Type", "Description"))
print("{:<20} {:<20}".format("torch.float32", "32-bit floating point"))
print("{:<20} {:<20}".format("torch.float64", "64-bit floating point"))
print("{:<20} {:<20}".format("torch.int32", "32-bit integer"))
print("{:<20} {:<20}".format("torch.int64", "64 bit integer"))
print("{:<20} {:<20}".format("torch.uint8", "8-bit unsigned integer"))
print("{:<20} {:<20}".format("torch.bool", "Boolean (True/False)"))


Tensor Data Types:
Data Type            Description         
torch.float32        32-bit floating point
torch.float64        64-bit floating point
torch.int32          32-bit integer      
torch.int64          64 bit integer      
torch.uint8          8-bit unsigned integer
torch.bool           Boolean (True/False)


### Mathematic Calculations 

In [137]:
a = torch.tensor([[1, 2, 3, 4000], [1, 2, 3, 4], [1, 2, 3, 4]])
b = torch.tensor([[2, 4, 5, 6000], [2, 4, 5, 6], [2, 4, 5, 6]])

In [ ]:
# add
a + 2


tensor([[1, 0, 1, 0],
        [1, 0, 1, 0],
        [1, 0, 1, 0]])

In [123]:
# sub
a - 2


tensor([[-1,  0,  1,  2],
        [-1,  0,  1,  2],
        [-1,  0,  1,  2]])

In [124]:
# division
a / 2


tensor([[0.5000, 1.0000, 1.5000, 2.0000],
        [0.5000, 1.0000, 1.5000, 2.0000],
        [0.5000, 1.0000, 1.5000, 2.0000]])

In [125]:
# power
a**2


tensor([[ 1,  4,  9, 16],
        [ 1,  4,  9, 16],
        [ 1,  4,  9, 16]])

In [126]:
# mod
a % 2

tensor([[1, 0, 1, 0],
        [1, 0, 1, 0],
        [1, 0, 1, 0]])

 ####  Mathematic operations between more than one tensor

In [127]:
a+b 

tensor([[ 3,  6,  8, 10],
        [ 3,  6,  8, 10],
        [ 3,  6,  8, 10]])

In [128]:
a-b

tensor([[-1, -2, -2, -2],
        [-1, -2, -2, -2],
        [-1, -2, -2, -2]])

In [129]:
a/b

tensor([[0.5000, 0.5000, 0.6000, 0.6667],
        [0.5000, 0.5000, 0.6000, 0.6667],
        [0.5000, 0.5000, 0.6000, 0.6667]])

In [139]:
a*b

tensor([[       2,        8,       15, 24000000],
        [       2,        8,       15,       24],
        [       2,        8,       15,       24]])

In [ ]:
a**b   # first row of third element will the zero because of data overflow range 

tensor([[   1,   16,  243,    0],
        [   1,   16,  243, 4096],
        [   1,   16,  243, 4096]])

In [140]:
a.to(torch.float64)

tensor([[1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+03],
        [1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00],
        [1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00]], dtype=torch.float64)

In [141]:
b.to(torch.float64)

tensor([[2.0000e+00, 4.0000e+00, 5.0000e+00, 6.0000e+03],
        [2.0000e+00, 4.0000e+00, 5.0000e+00, 6.0000e+00],
        [2.0000e+00, 4.0000e+00, 5.0000e+00, 6.0000e+00]], dtype=torch.float64)

In [ ]:
a**b   

tensor([[   1,   16,  243,    0],
        [   1,   16,  243, 4096],
        [   1,   16,  243, 4096]])